import type { AppState, Item } from "../src/types";
export const shirt: Item = {
  id: "top",
  name: "白色衬衫",
  category: "top",
  colors: ["白色"],
  seasons: [],
  occasions: [],
  tags: [],
  status: "available",
  confirmed: true,
  favorite: false,
  price: "120.00",
  currency: null,
  brand: "",
  closet: "日常衣橱",
  notes: "",
  purchased_at: null,
  created_at: "2026-09-09T00:00:00Z",
  updated_at: "2026-09-09T00:00:00Z",
  image_url: null,
  original_url: null,
  background_status: "skipped",
  ai_status: "idle",
  ai_error: null,
  wear_count: 0,
};
export const pants: Item = {
  ...shirt,
  id: "bottom",
  name: "蓝色长裤",
  category: "bottom",
  currency: "CNY",
};
export const shoe: Item = {
  ...shirt,
  id: "shoes",
  name: "白色运动鞋",
  category: "shoes",
  currency: "CNY",
};
export function fixture(): AppState {
  return {
    settings: {
      name: "",
      onboarded: false,
      language: "zh-CN",
      preferences: {
        location: "",
        temperature: 22,
        sensitivity: "normal",
        notes: "",
        excluded_ids: [],
        blocked_pairs: [],
        closet_scope: "all",
      },
    },
    items: [shirt, pants, shoe],
    outfits: [],
    plans: [],
    wear_events: [],
    trips: [],
    ai: {
      provider: "none",
      base_url: "",
      text_model: "",
      vision_model: "",
      has_key: false,
      capabilities: { text: false, vision: false },
      configured: false,
    },
    features: { background_removal: true, background_removal_ready: true },
    insights: {
      total: 3,
      available: 3,
      laundry: 0,
      unworn: 3,
      costs: [],
      categories: [
        { category: "top", count: 1 },
        { category: "bottom", count: 1 },
        { category: "shoes", count: 1 },
      ],
      colors: [],
      most_worn: [],
      unworn_items: [],
    },
  };
}
